add_definitions(
	-DMACOS_PLATFORM
	-DPOSIX_PLATFORM
)

#set (CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++11")
#set (CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++")
#set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -stdlib=libc++ -Wall -Wextra -Werror")